FROM nvcr.io/nvidia/cuda:12.5.0-runtime-ubuntu20.04

RUN apt update && apt upgrade -y && apt install -y build-essential linux-headers-generic dkms libncurses-dev gawk flex bison libssl-dev libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm dwarves

